# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("fcdex_3_1", "0015_tournament_max_participants")]

    operations = [
        migrations.CreateModel(
            name="TournamentConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "max_participants_cap",
                    models.PositiveIntegerField(
                        default=0, help_text="Upper limit for tournament max_participants. 0 = unlimited."
                    ),
                ),
                (
                    "semifinal_cutoff_cap",
                    models.PositiveIntegerField(
                        default=0, help_text="Upper limit for tournament semifinal_cutoff. 0 = unlimited."
                    ),
                ),
                (
                    "min_bet_cap",
                    models.PositiveIntegerField(
                        default=0, help_text="Upper limit for tournament min_bet. 0 = unlimited."
                    ),
                ),
                (
                    "max_bet_cap",
                    models.PositiveIntegerField(
                        default=0, help_text="Upper limit for tournament max_bet. 0 = unlimited."
                    ),
                ),
                (
                    "bet_payout_multiplier_cap",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Upper limit for tournament bet_payout_multiplier. 0 = unlimited."
                    ),
                ),
            ],
            options={"verbose_name": "Tournament config", "verbose_name_plural": "Tournament config"},
        )
    ]
