# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("fcdex_3_0", "0016_tournament_config")]

    operations = [
        migrations.AlterField(
            model_name="tournamentmatch",
            name="round",
            field=models.CharField(
                choices=[
                    ("group", "Group"),
                    ("quarterfinal", "Quarterfinal"),
                    ("semifinal", "Semifinal"),
                    ("final", "Final"),
                ],
                max_length=12,
            ),
        )
    ]
