# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("fcdex_3_1", "0017_tournament_round_quarterfinal")]

    operations = [
        migrations.AddField(
            model_name="sbcrecipe",
            name="recipe_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard (ball → ball)"),
                    ("clubball_to_custom", "Clubball → Custom"),
                    ("custom_to_card", "Custom → Card"),
                ],
                default="standard",
                max_length=20,
            ),
        )
    ]
